version: "3.8"
services:


    S1:
        build: ./S1
        image: husain98/s1:latest
        ports:
        - target: 5500
          published: 5500        
          protocol: tcp
        environment:
          DATABASE_URI: ${DATABASE_URI}

    S4:
        build: ./S4
        image: husain98/s4:latest
        ports:
        - target: 5050
          published: 5050        
          protocol: tcp             
                  
  
    
    S2:
        build: ./S2
        image: husain98/s2:latest
        ports:
        - target: 5000
          published: 5000
          protocol: tcp

    S3:
        build: ./S3
        image: husain98/s3:latest
        ports:
        - target: 5005
          published: 5005
          protocol: tcp
   
   