---
# tasks file for docker-worker
- name: Joinning The Swarm
  become: true
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    join_token: "{{ hostvars['manager']['swarm_info']['swarm_facts']['JoinTokens']['worker2'] }}"
    remote_addrs: [ 'manager:2377' ]